Life_Prescriber/Life_Prescriber/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

# Customize the admin site titles
admin.site.site_title = "Life Prescriber"
admin.site.site_header = "Life Prescriber Admin"
admin.site.index_title = "Welcome to Life Prescriber Admin"

urlpatterns = [
    path('life_prescriber_admin/', admin.site.urls),
    path('prescription_ongo/', include('prescription_ongo.urls', namespace="prescription")),
]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

Life_Prescriber/prescription_ongo/urls.py
from django.urls import path
from . import views2
from . import views

app_name = "prescription_ongo"

urlpatterns = [
    # general Homepage
    path('general_home/', views.GeneralHomeView.as_view(), name="general_home"),
    # clinic user functions
    path('prescribe/<int:prescription_id>', views.PrescribeView.as_view(), name="prescribe"),
    path('new_prescribe/<int:patient_id>', views.NewPrescribeView.as_view(), name="new_prescribe"),
    path('change_prescribe/<int:prescription_id>', views.ChangePrescribeView.as_view(), name="change_prescribe"),
    path('drug_used/<str:timer_token>/<uuid:clicked_token>', views.DrugUsedView.as_view(), name="drug_used"),

    # clinic user authentication
    path("custom_login/", views2.CustomLogin.as_view(template_name="prescription_ongo/custom_login.html"), name="custom_login"),
    path("custom_home/", views2.CustomHome.as_view(), name="custom_home"),
    path("custom_logout/", views2.CustomLogout.as_view(), name="custom_logout"),
    path("custom_ban/", views2.CustomBan.as_view(), name="custom_ban"),
    path("custom_password_reset/", views2.CustomPasswordReset.as_view(), name="custom_password_reset"),
    path("custom_password_reset_done/", views2.CustomPasswordResetDone.as_view(), name="custom_password_reset_done"),
    path("custom_reset/<str:uidb64>/<str:token>/", views2.CustomReset.as_view(), name="custom_reset"),
    path("custom_reset_done/", views2.CustomResetDone.as_view(), name="custom_reset_done"),
    path("custom_password_reset_warning/", views2.CustomPasswordResetWarning.as_view(), name="custom_password_reset_warning"),
    path("secret_add_user/<str:timer_token>", views2.SecretClinicUserAdd.as_view(), name="secret_add_user"),
    path("secret_delete_user/<str:timer_token>", views2.SecretClinicUserDelete.as_view(), name="secret_delete_user"),
    path("secret_search_patient/", views2.PharmacySecretSearch.as_view(), name="secret_search_patient"),
    path("user_prescription/<int:patient_id>", views2.UserPrescription.as_view(), name="user_prescription"),

    # patient user auths
    path('secret_search/<str:timer_token>', views.HospitalSecretSearch.as_view(), name="secret_search"),
    path('secret_signup/<str:timer_token>', views.HospitalSecretSignUp.as_view(), name="secret_signup"),
]

Life_Prescriber/prescription_ongo/forms.py
# forms.py
from django import forms
from .models import Prescribe, Patient, Insurance

class PrescribeForm(forms.ModelForm):
    class Meta:
        model = Prescribe
        fields = ["prescribe_time", "drug_name", "total_tablets", "no_of_times_per_day", "no_of_tablets_per_use", "general_description"]

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ["username"]

class SecretPatientRegisterForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ["first_name", "middle_name", "last_name", "username", "email", "insurance_id"]

class SecretInsuranceRegisterForm(forms.ModelForm):
    class Meta:
        model = Insurance
        fields = ["insurance_name"]

Life_Prescriber/prescription_ongo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib import messages
from django.urls import reverse
from .models import ClinicUser, OneTimeLink
from django.views import View
from .models import Patient, Prescribe
from .forms import PatientForm, PrescribeForm, SecretInsuranceRegisterForm, SecretPatientRegisterForm
from datetime import time, datetime, timedelta
from django.core.signing import BadSignature, SignatureExpired
from .utils import SIGNER
from .utils_2 import generate_secret_url, SIGNER_2
import math
from django.template.loader import render_to_string

# define utiity function
def send_back_error_with_previous_data(request, error_message):
    context_variable = {}
    patient_data = {"username": request.POST.get("username")}
    prescribe_data = {
        "prescribe_time": request.POST.get("prescribe_time"),
        "drug_name" : request.POST.get("drug_name"),
        "total_tablets": request.POST.get("total_tablets"),
        "no_of_times_per_day": request.POST.get("no_of_times_per_day"),
        "no_of_tablets_per_use": request.POST.get("no_of_tablets_per_use"),
        "general_description": request.POST.get("general_description"),
    }
    patient_form = PatientForm(patient_data)
    prescribe_form = PrescribeForm(prescribe_data)
    context_variable["patient_form"] = patient_form
    context_variable["prescribe_form"] = prescribe_form 
    context_variable["any_error"] = error_message
    return context_variable

def send_back_error_with_previous_data_2(request, error_message):
    context_variable = {}
    patient_data = {"username": request.POST.get("username")}
    prescribe_data = {
        "drug_name" : request.POST.get("drug_name"),
        "no_of_times_per_day": request.POST.get("no_of_times_per_day"),
        "no_of_tablets_per_use": request.POST.get("no_of_tablets_per_use"),
    }
    patient_form = PatientForm(patient_data)
    prescribe_form = PrescribeForm(prescribe_data)
    context_variable["patient_form"] = patient_form
    context_variable["prescribe_form"] = prescribe_form 
    context_variable["any_error"] = error_message
    return context_variable


# Create your views here.
class PrescribeView(View):
    template_name = "prescription_ongo/prescribtion.html"
    def get(self, request, prescription_id):
        if request.user.is_authenticated:
            # TODO: make sure you do what is in the docstring
            """
            check if cookies is expired and redirect them login as
            get request and after authentication new cookies are added,
            and we are sent to custom_home.
            """
            if not (request.COOKIES.get("custom_session", None) == "session_cookie") or \
                    not (request.COOKIES.get("custom_time", None) == "time_cookie"):
                login_url = reverse("prescription:custom_login")
                return redirect(login_url)
            """
            we need to know the user authenticated either django user
            or custom user.
            """
            if not isinstance(request.user, ClinicUser):
                login_url = reverse("prescription:custom_login")
                return redirect(login_url)

            """
            If both case come out False render the prescription form
            will add some context soon.
            """
            # use the prescription_id to get the prescription
            # and then get the username and drug_name
            user_prescription= Prescribe.objects.filter(
                id=prescription_id,
            ).first()

            context_variable = {}

            if user_prescription:
                patient_data = {
                    "username": user_prescription.prescribed_user.username,
                }
                prescribe_data = {
                    "drug_name": user_prescription.drug_name,
                }
                context_variable["patient"] = user_prescription.prescribed_user
                context_variable["patient_id"] = user_prescription.prescribed_user.id
            else:
                patient_data = {}
                prescribe_data = {}

            patient_form, prescribe_form = PatientForm(patient_data), PrescribeForm(prescribe_data)
            context_variable["patient_form"] = patient_form
            context_variable["prescribe_form"] = prescribe_form
            if request.session.get("success_message", None):
                context_variable["success_message"] = request.session["success_message"]
                del request.session["success_message"]
            return render(request, self.template_name, context_variable)
             
        login_url = reverse("prescription:custom_login")
        return redirect(login_url)

    def post(self, request, prescription_id):
        context_variable = None
        periods = ["am", "pm"]
        get_username_from_post = request.POST.get("username")
        check_username_exist = Patient.objects.filter(
            username=get_username_from_post,
        )
        patient_id = request.POST.get("patient_id")

        if not check_username_exist.exists():
            context_variable = send_back_error_with_previous_data(request, "This patient username doesn't exist.")
            context_variable["patient_id"] = patient_id
            return render(request, self.template_name, context_variable)
        
        get_prescribe_time_from_post = request.POST.get("prescribe_time")
        if len(get_prescribe_time_from_post) > 4:
            context_variable = send_back_error_with_previous_data(request, "prescribe time should be in this form <time><am|pm> e.g 08am or 08pm or 8pm or 8am.")
            context_variable["patient_id"] = patient_id
            return render(request, self.template_name, context_variable)
        
        # check if the first or first two characters can be converted to int
        try:
            try_convert = int(get_prescribe_time_from_post[0:2]) if len(get_prescribe_time_from_post) == 4 else int(get_prescribe_time_from_post[0])
        except ValueError:
                context_variable = send_back_error_with_previous_data(request, f"prescribe time should be in this form <time><am|pm> e.g 08am or 08pm or 8pm or 8am, inputed {get_prescribe_time_from_post}.")
                context_variable["patient_id"] = patient_id
                return render(request, self.template_name, context_variable)
        
        # check if the last 2 characters is am or pm
        period_value = get_prescribe_time_from_post[-2: ]
        if period_value.lower() not in periods:
            context_variable = send_back_error_with_previous_data(request, f"prescribe time should be in this form <time><am|pm> e.g 08am or 08pm or 8pm or 8am, inputed {get_prescribe_time_from_post}.")
            context_variable["patient_id"] = patient_id
            return render(request, self.template_name, context_variable)
        
        #  check if the try convert is between a range
        if not 1 <= try_convert <= 12:
            context_variable = send_back_error_with_previous_data(request, f"prescribe time should be in this form <time><am|pm> and  between range 1 to 12  e.g 08am or 08pm or 8pm or 8am, inputed {get_prescribe_time_from_post}.")
            context_variable["patient_id"] = patient_id
            return render(request, self.template_name, context_variable)  
                
        # now save all the data for the patient prescription
        if period_value.lower() == "am":
            start = 0 if try_convert == 12 else try_convert
            hour = 12 + 12 - 1 if try_convert == 12 else try_convert - 1
        else:
            start = 0 + try_convert if try_convert == 12 else try_convert + 12
            hour = 0 + 12 - 1 if try_convert == 12 else try_convert + 12 - 1
            
        first_time = time(hour=start, minute=0) # time the user takes drug
        prescribe_time = time(hour=hour, minute=50) # time notifications are sent
        drug_name = request.POST.get("drug_name")
        total_tablets =  request.POST.get("total_tablets")
        no_of_times_per_day =  request.POST.get("no_of_times_per_day")
        no_of_tablets_per_use =  request.POST.get("no_of_tablets_per_use")
        general_description =  request.POST.get("general_description")


        # calculate the initial_proposed_date, recent_proposed_date, start_time
        start_time = datetime.now()

        #TODO check this calculation for zero division error
        try:
            total_days = math.ceil(int(total_tablets) / (int(no_of_times_per_day) * int(no_of_tablets_per_use)))
        except ZeroDivisionError:
            context_variable = send_back_error_with_previous_data(request, "Invalid entry no_of_times_per_day or no_of_tablets_per_use cannot be 0.")
            context_variable["patient_id"] = patient_id
            return render(request, self.template_name, context_variable)
                 
        initial_proposed_date = start_time + timedelta(total_days - 1)
        recent_proposed_date = initial_proposed_date

        # check if the drug exist if it does just update rather than create new one 
        check_prescription_exists = Prescribe.objects.filter(
            prescribed_user=check_username_exist.first(),
            drug_name=drug_name.lower()
        ).exists()

        if check_prescription_exists:
            Prescribe.objects.filter(
                prescribed_user=check_username_exist.first(),
                drug_name=drug_name.lower()
            ).update(
                first_time=first_time,
                prescribe_time = prescribe_time,
                start_time=start_time,
                initial_proposed_date=initial_proposed_date,
                recent_proposed_date=recent_proposed_date,
                total_tablets=total_tablets,
                total_tablets_dynamic=total_tablets,
                no_of_times_per_day=no_of_times_per_day,

Life_Prescriber/prescription_ongo/templates/prescription_ongo/change_prescription.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Prescription</title>
    <link rel="stylesheet" href="{% static './styles/change_prescription.css' %}">
    <link rel="icon" type="image/png" href="{% static './images/logo_placeholder.png' %}">
    <script src="https://kit.fontawesome.com/95cc5340fb.js" crossorigin="anonymous"></script>
</head>

<body>
    {% if patient or any_error or success_message %}
    <main>
        <div class="main-form">
            <div class="logo-image">
                <img src="{% static './images/logo_placeholder.png' %}" alt="logo">
            </div>
            <div class="sub-image">
                <img src="{% static './images/prescription.jpg' %}" alt="prescription-image" class="prescription-image">
            </div>
            <div>
                <h1>Change Prescription</h1>
            </div>
            <div class="main-para">
                <p>Stay on track with every dose!</p>
            </div>

            <form method="post" action="">
                {% if any_error %}
                <div class="msg error-msg">
                    {{any_error}}
                </div>
                {% endif %}
                {% if success_message %}
                <div class="msg success-msg">
                    {{success_message}}
                </div>
                {% endif %}
                {% csrf_token %}
                <div>
                    <div class="form-group no-focus">
                        {{patient_form.username.label_tag}}
                        {{patient_form.username}}
                    </div>
                    <div class="form-group no-focus">
                        {{prescribe_form.drug_name.label_tag}}
                        {{prescribe_form.drug_name}}
                    </div>
                    <div class="form-group">
                        {{prescribe_form.no_of_times_per_day.label_tag}}
                        {{prescribe_form.no_of_times_per_day}}
                    </div>
                    <div class="form-group">
                        {{prescribe_form.no_of_tablets_per_use.label_tag}}
                        {{prescribe_form.no_of_tablets_per_use}}
                    </div>
                    <div class="form-group" style="display: none;">
                        <label for="patient-id">patient id</label>
                        <input type="hidden" name="patient_id" value="{{patient_id}}" id="patient-id">
                    </div>
                </div>
                <div class="btn">
                    <div>
                        <button type="submit" class="submit-btn">Submit<i
                                class="fa-solid fa-location-arrow"></i></button>
                    </div>

                    <button type="button" class="home-btn">
                        <a href="{% url 'prescription:user_prescription' patient_id %}"
                            style="text-decoration: none;"><i class="fa-solid fa-circle-chevron-left"></i>Back</a>
                    </button>

                </div>
            </form>
        </div>
    </main>
    {% else %}
    <div class="btn not-found">
        <p>Patient data doesn't exist!</p>
        <button type="button" class="home-btn not-found-btn">
            <a href="{% url 'prescription:custom_home' %}" style="text-decoration: none;"><i
                    class="fa-solid fa-circle-chevron-left"></i> Go Home</a>
        </button>
    </div>
    {% endif %}
</body>

</html>

Life_Prescriber/prescription_ongo/templates/prescription_ongo/custom_password_reset_email.html
This is a no reply email
Someone asked for password reset for email {{ email }}. Follow the link below:
{% if reset_url %}
    {{ reset_url }}
{% endif %}

Life_Prescriber/prescription_ongo/templates/prescription_ongo/general_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=div, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './styles/general_home.css' %}" type="text/css">
    <link rel="icon" type="image/png" href="{% static './images/logo_placeholder.png' %}">
    <script src="https://kit.fontawesome.com/95cc5340fb.js" crossorigin="anonymous"></script>
    <title>Clinicians Login</title>
</head>

<body>
    <div class="form-container">
        <div class="main-form">
            <div class="logo-image">
                <img src="{% static './images/logo_placeholder.png' %}" alt="life_prescriber">
                <p>Life Prescriber™</p>
            </div>
            <div class="form-header" id="typing-effect">
            </div>
            <div class="forms-div">
                <div class="notification">
                    <div class="notification-msg">
                        {% include 'prescription_ongo/messages.html' %}
                    </div>
                </div>
                {% if error_message %}
                <div class="last-error-msg">
                    <p class="alert err-msg">{{error_message}}</p>
                </div>
                {% endif %}
                <form method="post" action="{% url 'prescription:general_home' %}">
                    {% csrf_token %}
                    <div>
                        <div class="form-group">
                            <label for="clinic_username_or_email">
                                Username or Email
                            </label>
                            <input type="text" name="username_or_email" id="clinic_username_or_email">
                        </div>
                        <div class="form-group">
                            <label for="clinic_password">
                                Password
                            </label>
                            <input type="password" name="password" id="clinic_password">
                        </div>
                        <div class="back-link-btn">
                            <p>
                                <a href="{% url 'prescription:custom_home' %}">Go to Login</a>
                            </p>
                        </div>
                    </div>

                    <div class="btn">
                        <button type="submit" class="submit-btn">
                            Verify details
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% if success_message %}
        <div id="fixed-notification-box" class="hidden">
            <div class="fixed-notification-close"><i class="fa-solid fa-circle-xmark"></i></div>

            <div class="fixed-notification-content">
                <div class="notification-below">
                    <div class="notification-msg-below">
                        {% include 'prescription_ongo/messages.html' %}
                    </div>
                    <div class="notification-msg-para">
                        <p>Proceed to Hospital Portal or Pharmacy Portal below to view patients details or add users</p>
                    </div>
                </div>
                <div class="fixed-notification-tabs">
                    <div class="tab-box">
                        <a href="{% url 'prescription:secret_search' clinic_timer_token %}">
                            Hospital Portal
                        </a>
                    </div>
                    <div class="tab-box">
                        <a href="{% url 'prescription:secret_add_user' pharmacy_timer_token %}">
                            Pharmacy Portal
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</body>
{% if first_get_request %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const textElement = document.getElementById('typing-effect');
        const text = 'Are you a Pharmacy or Hospital?';
        const typingSpeed = 100; // Milliseconds per character
        const isFirstLoad = true;

        if (isFirstLoad) {
            let charIndex = 0;

            function type() {
                if (charIndex < text.length) {
                    textElement.textContent += text.charAt(charIndex);
                    charIndex++;
                    setTimeout(type, typingSpeed);
                } else {
                    localStorage.setItem('isFirstLoad', 'false');
                }
            }

            type();
        } else {
            textElement.textContent = text;
        }
    });
</script>
{% else %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const textElement = document.getElementById('typing-effect');
        const text = 'Are you a Pharmacy or Hospital?';
        const typingSpeed = 100; // Milliseconds per character
        const isFirstLoad = false;

        if (isFirstLoad) {
            let charIndex = 0;

            function type() {
                if (charIndex < text.length) {
                    textElement.textContent += text.charAt(charIndex);
                    charIndex++;
                    setTimeout(type, typingSpeed);
                } else {
                    localStorage.setItem('isFirstLoad', 'false');
                }
            }

            type();
        } else {
            textElement.textContent = text;
        }
    });
</script>
{% endif %}
{% if success_message %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const notificationBox = document.getElementById('fixed-notification-box');
        const notificationClose = notificationBox.querySelector(".fixed-notification-close");
        const iconTag = notificationClose.querySelector('i');
        const mainForm = document.querySelector('.main-form');

        iconTag.addEventListener("click", (e) => {
            notificationBox.classList.add('hidden');
            notificationBox.classList.remove('visible');
            mainForm.classList.remove('blur');
        })
        notificationBox.classList.add('visible');
        notificationBox.classList.remove('hidden');
        mainForm.classList.add('blur');
    });

</script>
{% endif %}

</html>

Life_Prescriber/prescription_ongo/templates/prescription_ongo/messages.html
{% if messages %}
<div class="messages space-y-4">
    {% for message in messages %}
        {% if 'success' in message.tags %}
            <div class="alert success-msg" role="alert">
                <span>Success: {{ message }}</span>
            </div>
        {% elif 'error' in message.tags %}
            <div class="alert err-msg" role="alert">
                <span>Error: {{ message }}</span>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

Life_Prescriber/prescription_ongo/templates/prescription_ongo/user_prescription.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prescriptions</title>
    <link rel="stylesheet" href="{% static './styles/user_prescription.css' %}">
    <link rel="icon" type="image/png" href="{% static './images/logo_placeholder.png' %}">
    <script src="https://kit.fontawesome.com/95cc5340fb.js" crossorigin="anonymous"></script>
</head>

<body>
    {% if patient and all_prescriptions %}
    <div class="container">
        <div class="header">
            <div class="name-header">
                <h1>{{ patient_first_name }} {{ patient_last_name }}</h1>
            </div>
            <div class="new-prescription-header">
                <h2><span class="prescription-text">Prescriptions</span></h2>
                <div class="box">
                    <button type="button" id="search-button"
                        data-url="{% url 'prescription:user_prescription' patient.id %}">
                        <i class="fa-solid fa-magnifying-glass icon"></i>
                    </button>
                    <label style="display: none;" for="search-box"></label>
                    <input type="text" name="drug-search" id="search-box"
                        placeholder="search">
                </div>
                <button class="new-prescription-btn">
                    <a href="{% url 'prescription:new_prescribe' patient.id %}">Add New<i
                            class="fa-solid fa-plus"></i></a>
                </button>
            </div>
        </div>
        <div class="prescriptions">
            <!-- Iterate over your prescriptions queryset here -->
            {% for prescription in all_prescriptions %}
            <div class="prescription-card">
                <!-- <h2>{{ prescription.prescribed_user.first_name }} {{ prescription.prescribed_user.last_name }}</h2> -->
                <div class="details">
                    <div class="details-start-date">
                        <p>{{ prescription.start_time|date:"d" }}</p>
                        <p>{{ prescription.start_time|date:"M" }}</p>
                        <p>{{ prescription.start_time|date:"g:i A" }}</p>
                    </div>

                    <div class="details-tablet">
                        <div class="drug-name">
                            <p>{{ prescription.drug_name }}</p>
                        </div>

                        <div class="drug-time">
                            <div class="drug-reminder-time">
                                <img src="{% static './images/reminder.png' %}" alt="reminder">
                                <p>{{ prescription.prescribe_time }}</p>
                            </div>

                            <div class="drug-use-time">
                                <p><i class="fa-solid fa-clock"></i> {{ prescription.first_time }}</p>
                            </div>
                        </div>

                        <div class="drug-end-date">
                            <p><span class="inner-text">End Date: </span>{{ prescription.recent_proposed_date|date:"d"}}
                            </p>
                            <p>{{ prescription.recent_proposed_date|date:"F" }}</p>
                        </div>

                        <div class="drug-total-tablets">
                            <div class="total-pill-tablets">
                                <p><span class="inner-text">Total Tablet: </span>{{ prescription.total_tablets }}</p>
                            </div>
                            <div class="total-tablets-left">
                                <img src="{% static './images/tablets.png' %}" alt="total_tablets">
                                <p>{{ prescription.total_tablets_dynamic }}</p>
                            </div>
                        </div>

                        <div class="drugs-per-use">
                            <p><span class="inner-text">Per Day: </span>{{ prescription.no_of_times_per_day }}</p>
                            <p><span class="inner-text">Per Use: </span>{{ prescription.no_of_tablets_per_use }}</p>
                        </div>
                        <!-- <p><strong>Start Time Date:</strong> {{ prescription.start_time }}</p> -->

                        <!-- <p><strong>Initial Proposed Date:</strong> {{ prescription.initial_proposed_date }}</p> -->
                    </div>

                </div>
                <div class="actions">
                    {% if prescription.total_tablets_dynamic == 0 %}
                    <a href="{% url 'prescription:prescribe' prescription.id %}" class="edit-btn"><i
                            class="fa-solid fa-pen-to-square"></i></a> <!--Make new prescription (from old) -->
                    {% else %}
                    <a href="{% url 'prescription:change_prescribe' prescription.id %}" class="edit-btn"><i
                            class="fa-solid fa-pen-to-square"></i></a> <!--Change Old prescription (from
                    old) -->
                    {% endif %}
                    <!-- <button class="edit-btn">Edit</button> -->
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="btn">
            <button type="button" class="home-btn">
                <a href="{% url 'prescription:custom_home' %}" style="text-decoration: none;"><i
                        class="fa-solid fa-circle-chevron-left"></i> Back Home</a>
            </button>
        </div>
    </div>
    {% elif patient and not all_prescriptions %}
    <div class="not-found">
        <p>No Prescription(s) found for this user</p>
        <button class="new-prescription-btn">
            <a href="{% url 'prescription:new_prescribe' patient.id %}">Add New<i class="fa-solid fa-plus"></i></a>
        </button>
    </div>
    {% else %}
    <div class="btn not-found">
        <p>Patient not found!</p>
        <button type="button" class="home-btn">
            <a href="{% url 'prescription:custom_home' %}" style="text-decoration: none;"><i
                    class="fa-solid fa-circle-chevron-left"></i> Go Home</a>
        </button>
    </div>
    {% endif %}
</body>
<script>
    const searchButton = document.querySelector("#search-button");
    searchButton.addEventListener("click", (eventObject) => {
        const dataUrl = eventObject.currentTarget.getAttribute("data-url");
        const searchBox = document.querySelector("#search-box");
        const searchQuery = searchBox.value;
        const searchDataUrl = `${dataUrl}?search=${searchQuery}`;
        window.location.href = searchDataUrl;
    })
</script>

</html>